### ISSUE TITLE
publish new version to npm registry

### ISSUE THREAD

**Issue by GGAlanSmithee** [IceCreamYou/MainLoop.js#2]
Hi!

I see you added "main" in package.json about 2 months ago, but you have not published a new package to the npm registry.

So after doing "npm install mainloop.js" I still had to add main to use your lib.

Could you please publish a newer version of this package to the npm registry?

Thanks.

**Comment by IceCreamYou** [comment]
I updated it just now, but for some reason npm thinks 1.0.0 is the latest release, so you'll need to `npm install mainloop.js@1.0.1` for now. I sent a support request... maybe it will fix itself in a bit.

**Comment by GGAlanSmithee** [comment]
Thanks

**Comment by IceCreamYou** [comment]
Thanks to npm support, the latest release is now set to 1.0.1 so you can just `npm install mainloop.js` :smiley:
