### ISSUE TITLE
mainloop server-side not working because of "window"

### ISSUE THREAD

**Issue by Djedjeska** [IceCreamYou/MainLoop.js#21]
Hello, the documentation says that it can be used in Node.js with require('mainloop')
But when I tested, it simply isn't possible because of the use of "window', which obviously isn't available server-side...

**Comment by IceCreamYou** [comment]
MainLoop.js does not depend on `window`. It includes a fallback for cases where `window` is not present. This works for me:

```javascript
$ node --version
v10.15.2
$ node
> var MainLoop = require('MainLoop.js');
undefined
> var now = Date.now();
undefined
> MainLoop.setUpdate((delta) => {
...   if (Date.now() > now + 1000) {
.....   console.log('done');
.....   MainLoop.stop();
..... }
... }).start();
{ getSimulationTimestep: [Function: getSimulationTimestep],
  setSimulationTimestep: [Function: setSimulationTimestep],
  getFPS: [Function: getFPS],
  getMaxAllowedFPS: [Function: getMaxAllowedFPS],
  setMaxAllowedFPS: [Function: setMaxAllowedFPS],
  resetFrameDelta: [Function: resetFrameDelta],
  setBegin: [Function: setBegin],
  setUpdate: [Function: setUpdate],
  setDraw: [Function: setDraw],
  setEnd: [Function: setEnd],
  start: [Function: start],
  stop: [Function: stop],
  isRunning: [Function: isRunning] }
done
```

If you are encountering a specific error, I may be able to provide more assistance if you post the error message.

**Comment by Djedjeska** [comment]
Hello ICY and thanks for your answer. 
When I run the code in my project, here is the error I get :

Starting child process with 'node app.js'
Watching directory '/Users/cgptools/Desktop/Projets/Gameloop' for changes.
Press rs for restarting the process.
/Users/cgptools/Desktop/Projets/Gameloop/node_modules/MainLoop/mainloop.js:22
    var requestAnimationFrame = window.requestAnimationFrame,
                                ^

ReferenceError: window is not defined
    at /Users/cgptools/Desktop/Projets/Gameloop/node_modules/MainLoop/mainloop.js:22:33
    at /Users/cgptools/Desktop/Projets/Gameloop/node_modules/MainLoop/mainloop.js:12:26
    at Object.<anonymous> (/Users/cgptools/Desktop/Projets/Gameloop/node_modules/MainLoop/mainloop.js:19:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
Program node app.js exited with code 1

**Comment by Djedjeska** [comment]
Ok I'm sorry I think I somehow managed to mix up "mainloop" and "mainloop.js"
I was doing require("mainloop") and it seems to be another project
When I do require("mainloop.js") everything is fine.
Thank you very much

**Comment by IceCreamYou** [comment]
Ah, the README had `require('mainloop')` but you're right, it looks like it has to be `require('mainloop.js')`. I'll fix it!
