### ISSUE TITLE
port to Rust / WASM

### ISSUE THREAD

**Issue by dakom** [IceCreamYou/MainLoop.js#23]
would love to have this for rust/wasm projects... 

If I go for it, how should I handle the license? (happy for it to be MIT too)

of course it would mostly be copy/paste and I want to give you full credit for all the hard work you put into it - but Rust/WASM has its own set of problems that need some original solutions too.

**Comment by IceCreamYou** [comment]
Absolutely, go for it. Since this project is MIT-licensed, the easiest thing is to make your version MIT-licensed as well. There are other options, particularly dual-licensing, if you prefer.

**Comment by dakom** [comment]
ah I see: https://softwareengineering.stackexchange.com/questions/306695/mit-license-dual-authors

:)
