### ISSUE TITLE
Why does interpolation cycle?

### ISSUE THREAD

**Issue by dakom** [IceCreamYou/MainLoop.js#25]
Just trying to understand a bit, here's a simple demo that just writes values:

https://codepen.io/dakom/pen/GVomge?editors=0010

The interpolation amount passed to draw seems to sort of cycle, but not within one second, rather, resets after a while.

Can someone please explain a bit more why this is and what's happening under the hood?

Thanks!

**Comment by IceCreamYou** [comment]
That value is `frameDelta / simulationTimestep`. `frameDelta` is the elapsed time that hasn't been simulated by `update` yet, and `simulationTimestep` is the amount of time processed by each `update`. So essentially the value is the percent of an `update` that hasn't been simulated yet. If the amount of time between frames is anything other than exactly `simulationTimestep`, which will always be the case in practice for at least some frames, then the difference will cause a change in the interpolation amount. At ~60fps the change is very small in each frame, so you see the interpolation amount creeping up slowly from 0 to 1. Once it reaches 1, there is enough accumulated unsimulated time for another `update`, bringing the value back down to zero. However, the cyclic pattern is not guaranteed or monotonic; it just happens to be the case that with your demo code and under the conditions in which you ran your demo, the time between frames happens to be consistently slightly more than `simulationTimestep`. Under other conditions the time between frames could vary, or it could be below `simulationTimestep`, or it could be different enough (e.g. 25ms) that a pattern is not easily discernible.

**Comment by dakom** [comment]
Followup question with the same demo - why does `delta` always increase in `begin`?

The docs define this as: "The total elapsed time that has not yet been simulated, in milliseconds"

I don't quite get what it means that there is a constantly growing value of "elapsed time that has not yet been simulated"

**Comment by IceCreamYou** [comment]
`delta` does not always increase in `begin`. Not sure what you're referring to. When I open your demo, `delta` hovers in the 16-33ms range, which is normal for a program running at ~60fps; it basically means there's one frame's worth of time to process just before each frame, which is what you'd expect.

**Comment by dakom** [comment]
Ah - I saw it climbing and didn't wait long enough to see it come back around ;)

thanks!
