### ISSUE TITLE
Jank (esp in firefox)

### ISSUE THREAD

**Issue by dakom** [IceCreamYou/MainLoop.js#26]
I put together a minimal example: https://github.com/dakom/mainloop-test

and it's suuper janky in firefox at least. any idea why that is?

**Comment by IceCreamYou** [comment]
It runs at a pretty even 60fps for me in Firefox and Chrome. Try restarting Firefox - it could be that it's using too much memory or something like that and that's slowing everything down. If that doesn't work, and your computer has sufficient resources, take a look at the Performance tab of the Firefox dev tools and see if you can spot something that looks like it's causing the slowdown.

**Comment by dakom** [comment]
When you let it run for a minute or so, you don't see any visual jank in firefox?

Everything looks good in performance and various logs, but visually it stutters.

Maybe due to the meltdown/spectre mitigations?

**Comment by IceCreamYou** [comment]
> When you let it run for a minute or so, you don't see any visual jank in firefox?

Yes, I don't see visual jank in Firefox even after running your demo for several minutes.

If you're seeing 60 FPS in dev tools but the visuals are jumping around, and you haven't adjusted MainLoop's own maximum FPS or timestep settings and aren't seeing panics, then most likely there's some kind of accumulated error in how `position` is updated. From looking at the code I don't see how that would happen, but any other possibilities I can think of would all slow down the frame rate displayed in dev tools.
