### ISSUE TITLE
Where is the good place to have Websocket send() calls with the library?

### ISSUE THREAD

**Issue by niamleeson** [IceCreamYou/MainLoop.js#27]
Hello!

Your article on game time step helped me so much when I was making a small game. Thank you for the article and this awesome library!

I am trying to make a multiplayer game with Websocket and I'm not sure where would be the ideal place to put the socket.send() calls. The game updates at fixed time step, and draws at 60fps. I would like to send the player inputs to the authoritative server at 30hz instead of 60hz. Is this possible to do with this library?

Thank you for your help!

**Comment by IceCreamYou** [comment]
This library doesn't specifically provide a way to run a callback at multiple different frequencies. In your case it is probably sufficient to just do something like this in a `begin` callback:

```js
var lastSend = performance.now();
function begin() {
	var now = performance.now();
	if (now > lastSend + 30) {
		sendData();
		lastSend = now;
	}
}
```

This will send your data no more frequently than every 30ms, and if you're running at a smooth 60 FPS it'll send 30 times per second.

**Comment by niamleeson** [comment]
Thank you!
