### ISSUE TITLE
why such a big dip every few seconds in fps?

### ISSUE THREAD

**Issue by simon-kyger** [IceCreamYou/MainLoop.js#28]
Hello

I tried running your demo version of this loop on a 144hz monitor and occasionally am getting 100+ fps even if the slider is set to 60.

Am I misunderstanding what this will do for you or is this a bug?

This is roughly what I see happening:

![image](https://user-images.githubusercontent.com/13419651/67150186-2c097b80-f282-11e9-8f66-0afb43796444.png)

**Comment by IceCreamYou** [comment]
When the slider is set to max, the demo intentionally does not cap the FPS:

https://github.com/IceCreamYou/MainLoop.js/blob/gh-pages/demo/index.html#L253
