### ISSUE TITLE
Making loop run at an accelerated rate

### ISSUE THREAD

**Issue by andywilsonuk** [IceCreamYou/MainLoop.js#32]
Hi,

I've been trying to force the loop to execute more quickly so that I can test my game code at a faster rate (game runs twice as fast for example). I've tried updating the simulated timestep and/or max FPS but I think there's a throttle built into MainLoop which is actively preventing me from running too quickly.

Do you have any tips on what I can do?

Many thanks!
Andy

**Comment by IceCreamYou** [comment]
Hi Andy. If you call `MainLoop.setSimulationTimestep(1000 / 120).setMaxAllowedFPS(120)` (ideally before `MainLoop.start()`) and your loop is running at less than 120FPS, it's either because your application runs slower or your browser or monitor does not support running faster.

You can run the code below in a browser console to see how fast you can go. Without using `MainLoop.js`, it just logs the FPS to the console on every frame.

```js
var fps = 60, fpsAlpha = 0.9, lastTimestamp;
requestAnimationFrame(function animate(timestamp) {
    if (!lastTimestamp) lastTimestamp = timestamp - 1;
    fps = fpsAlpha * 1000 / (timestamp - lastTimestamp) + (1 - fpsAlpha) * fps;
    lastTimestamp = timestamp;
    console.log(fps);
    requestAnimationFrame(animate);
});
```

**Comment by IceCreamYou** [comment]
Closing this issue, but feel free to reopen if you can get a significantly faster frame rate with the code above than with an empty MainLoop under the same circumstances.

**Comment by andywilsonuk** [comment]
I'm getting 60 FPS (which my monitor is limited to), however I'm not really sure that I've explained what I'm trying to do properly. Basically I want to force the game to run at double speed for testing purposes, it's an Idle type game so there's lots of waiting for stuff to make/complete.

Perhaps to do what I want I should wrap the function called by setUpdate to actually do two frame updates, for example:

```javascript
var updateFn = (delta) => ... // updates the game

var doubleTimeFn = (delta) => {
  updateFn(delta)
  updateFn(delta) // called a second time to double the speed
}

MainLoop.setUpdate(doubleTimeFn)
```

Under normal game play ```setUpdate``` would reference ```updateFn``` and only during speed testing would ```setUpdate``` to set to ```doubleTimeFn```. 

Do you see what I mean?

**Comment by IceCreamYou** [comment]
Ah, yeah. You could just write something like `doubleTimeFn = (delta) => updateFn(delta * 2)` in that case to simulate twice as much time per update without doing twice the work.
