### ISSUE TITLE
The right way to use fps insensitive timeout or interval timers

### ISSUE THREAD

**Issue by frenzzy** [IceCreamYou/MainLoop.js#39]
For example I need to perform a specific action every game second:
```js
function update(dt) {
  if (/* what to check here? */) {
    console.log('this message is logged every second')
  }
}
```

**Comment by IceCreamYou** [comment]
This is not a MainLoop.js question. You would need to do the same thing inside setInterval or a requestAnimationFrame loop.

Anyway, one option is to do something like this:

```js
let lastCheck = performance.now();
function update() {
    const now = performance.now();
    if (now > lastCheck + 1000) {
        // do whatever you want here
        lastCheck = now;
    }
}
```

Alternatively if you are just interested in console logs that don't fire on every frame, you may be interested in https://github.com/unconed/console-extras.js

**Comment by frenzzy** [comment]
Thank you for the quick response! [console-extras.js](https://github.com/unconed/console-extras.js) is cool, did not know about it, thanks!

I was looking for a way to execute something every game second and not just every real clock second.
For example if the system will freeze for 5 seconds, mainLoop will execute update function (5 * fps) times while a single tick.
The game timer should execute every (1 * fps) update call, i.e. 5 times in total and not just once as in your example.

Maybe the solution should look something like this instead, what do you think?
```js
let timer = 0
let delay = 0
function update(dt) {
  timer += dt
  if (timer >= delay) {
    delay += 1000
    // do whatever you want here
  }
}
```

**Comment by IceCreamYou** [comment]
Ah, I see. Yes, that seems like it would work.
