### ISSUE TITLE
Designing a networked (Node.js) main loop for multiplayer capability

### ISSUE THREAD

**Issue by emilklindt** [IceCreamYou/MainLoop.js#7]
Hey Isaac!

Thanks a lot for this awesome repository. How would you suggest going about a Node.js implementation? I can't quite figure out the best way to do this.

I'm currently running an interval on the server-side, which streams out data to the client-side, which will then render the game (as for now). But as you probably know, this is not the best solution.

Basically I need to figure out a way to stream updates from server-side to client-side, and then render it in the most efficient way.

Any input is much appreciated!

**Comment by IceCreamYou** [comment]
Glad you like the library!

MainLoop.js should work in Node. I think what you're asking is how to design a networked game? Networking is Hard (TM). I wrote part of a chapter in [my book](http://smile.amazon.com/Game-Development-Three-js-Isaac-Sukin-ebook/dp/B00G58JD4K/) about it. There are a lot of things to consider and it depends also on what kind of game you're building. Here is an excerpt from my book:

>  RTS and turn-based games usually use an approach called lock-step, which is a peer-to-peer model in which each computer in a match sends its commands to all the other computers in the match. The main strength of this model is that only a small amount of data (the players' commands) needs to be sent over the network, so it is useful when the game state is huge (for example, when there are thousands of units in a map). However, running a game in lock-step depends on all players having an identical copy of the game state...
> 
> The other approach to game networking is a client-server prediction model, which usually works like this:
> 1. The client triggers some input (such as pressing a key or moving the mouse) that changes the game state.
> 2. The client input is sent to the server.
> 3. Optionally, the server forwards the input to the other clients.
> 4. The server processes the inputs it receives from all players, reconciles them, and produces a new, authoritative description of the game's state at a specific time.
> 5. If the server forwarded other clients' inputs, the clients receive those inputs and continue updating the local game state by predicting what the server thinks the state should be.
> 6. The server periodically sends the latest complete description of the authoritative game state to each client.
> 7. The client adjusts its state to sync with the server's official state.
> 
> The main difference here compared to lock-step is that clients can advance the game independently, and the entire game state can be sent from the server to ensure each player sees something pretty close to what the others see. This is a better model for action games like FPSs or games with many players like MMOs because players generally experience less dramatic latency effects.

I can't quote the whole chapter here, but it goes into how the naive client-server model produces lag, and techniques for mitigating that. Here are some useful resources for learning more on that subject:

> For more information on lock-step, check out http://www.altdevblogaday.com/2011/07/09/synchronous-rts-enginesand-a-tale-of-desyncs/
> and http://www.altdevblogaday.com/2011/07/24/synchronous-rts-engines-2-sync-harder/.
> 
> For more information about client-server prediction, check out http://gafferongames.com/networking-for-game-programmers/what-every-programmer-needs-to-know-about-gamenetworking/.
> 
> To learn about interpolating between authoritative and client states, see http://www.gamedev.net/page/resources/_/technical/multiplayer-and-network-programming/defeating-lagwith-cubic-splines-r914.
> 
> There is a great Google Tech Talk by Rob Hawkes on HTML5 multiplayer game development with many tips about overcoming common pitfalls. You can watch it at https://www.youtube.com/watch?v=zj1qTrpuXJ8.

In a client-server model, the key thing that's specific to MainLoop.js is that you should be running it both on the client and on the server. Clients should send their inputs to the server, the server should send the authoritative state back to the client, and then the client should interpolate towards that state while independently advancing the action.

Hope that helps.
