### ISSUE TITLE
bower install MainLoop doesn't work

### ISSUE THREAD

**Issue by sjlynch** [IceCreamYou/MainLoop.js#9]
Minor nitpick, but "bower install MainLoop" doesn't actually work (at least, not in git bash) but..

"bower install mainloop" DOES work. Is this an issue affecting everyone or just git bash users?

**Comment by jamesplease** [comment]
The reason for this is because Bower package names are case-sensitive.

**Comment by sjlynch** [comment]
Right, so maybe the readme should change

"bower install MainLoop"
to 
"bower install mainloop" ?

Obviously not a big deal, but still.

**Comment by jamesplease** [comment]
Ah, I didn't notice the issue in the readme! Good catch @sjlynch :)

I opened a PR here: https://github.com/IceCreamYou/MainLoop.js/pull/10

**Comment by IceCreamYou** [comment]
Thanks for the report and PR :) Merged #10

**Comment by jamesplease** [comment]
:v: thanks for the merge @IceCreamYou
